version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-s3: circleci/aws-s3@2.0.0 # use the AWS S3 orb in your config
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn build index.html
      - persist_to_workspace:
        root: dist
        paths:
          - dist/*
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - aws-s3/sync:
          from: dist
          to: 's3://kenhoff-github-searcher/'
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
