version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-s3: circleci/aws-s3@2.0.0 # use the AWS S3 orb in your config
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      # checking to see if the build installs, succeeds, and tests without error.
      # todo: persist bundle between job steps
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn build index.html
      # - run: yarn test
  deploy:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      # performing the same checkout, install, build step to avoid persisting between steps
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn build index.html
      - aws-s3/sync:
          from: dist
          to: 's3://kenhoff-github-searcher/'
workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: /^master$/
