version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - yarn install --frozen-lockfile
workflows:
  built:
    jobs:
      - build
