version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run: yarn install --frozen-lockfile
      - run: yarn build index.html
workflows:
  build:
    jobs:
      - build
